name: Pytest CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Cloner le dépôt
      uses: actions/checkout@v3

    - name: Configurer Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.x'

    - name: Installer les dépendances
      run: |
        pip install --upgrade pip
        pip install -r requirements.txt

    - name: Lancer les tests avec pytest
      run: pytest --html=report.html --self-contained-html

    - name: Télécharger le rapport HTML
      uses: actions/upload-artifact@v3
      with:
        name: pytest-report
        path: report.html
